# Generated by Django 5.0.3 on 2024-05-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='split',
            field=models.CharField(choices=[('PU', 'Push'), ('PL', 'Pull'), ('LG', 'Legs')], default='PU', max_length=2),
        ),
        migrations.RemoveField(
            model_name='workout',
            name='calories',
        ),
        migrations.DeleteModel(
            name='Split',
        ),
    ]
