# Generated by Django 5.0.3 on 2024-05-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_workout_split_remove_workout_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
    ]
