# Generated by Django 5.0.3 on 2024-05-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_workout_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lift',
            old_name='name',
            new_name='lift',
        ),
    ]
