# Generated by Django 5.0.3 on 2024-05-09 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_name_lift_lift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lift',
            old_name='reps',
            new_name='sets',
        ),
        migrations.RemoveField(
            model_name='lift',
            name='weight',
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('reps', models.IntegerField()),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lift')),
            ],
        ),
    ]
