# Generated by Django 5.0.3 on 2024-05-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_reps_lift_sets_remove_lift_weight_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='split',
            field=models.CharField(choices=[('PU', 'Push'), ('PL', 'Pull'), ('LG', 'Legs'), ('AR', 'Arms')], default='PU', max_length=2),
        ),
    ]
