# Generated by Django 5.0.3 on 2024-05-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_workout_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyweight',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
