# Generated by Django 5.0.6 on 2024-05-18 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_bodyweight_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='lift',
            name='lift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.liftname'),
        ),
    ]
