# Generated by Django 5.0.3 on 2024-05-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_liftname_alter_lift_lift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='lift',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='LiftName',
        ),
    ]
